# 13/30 Numpy et Broadcasting

In [ ]:
import numpy as np

In [ ]:
A = np.ones((2, 3))
B = 3
print(A+B) # résultat 1

A = np.ones((2, 3))
B = np.ones((2, 1)) # B a une colonne, elle sera étendu sur les trois colonnes de A
print(A+B) # résultat 2

A = np.ones((2, 3))
B = np.ones((2, 2))


[[4. 4. 4.]
 [4. 4. 4.]]
[[2. 2. 2.]
 [2. 2. 2.]]
